<a href="https://colab.research.google.com/github/Soumo31428/NaiveBayesImplementation/blob/main/Naive_Baye's_Algorithm_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Naive Baye's Machine Learning Algorithms Implementation

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [ ]:
x,y = load_iris(return_X_y=True)

In [ ]:
xtrain, xtest, ytrain, ytest  = train_test_split(x,y,test_size = 0.3, random_state = 10)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(xtrain, ytrain)
y_pred = gnb.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(confusion_matrix(y_pred, ytest))
print(accuracy_score(y_pred, ytest))
print(classification_report(y_pred, ytest))

[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



# Applying Naive Baye's on 'tips' dataset

In [ ]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
## categorize into independent and dependent feature
x = df.drop('sex',axis = 1)
y = df['sex']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest  = train_test_split(x,y,test_size = 0.3, random_state = 10)

### Feature Encoding

In [ ]:
## Label Encoding
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [ ]:
# Fit on xtrain and transform both xtrain and xtest

xtrain['smoker'] = le2.fit_transform(xtrain['smoker'])
xtest['smoker'] = le2.transform(xtest['smoker'])

xtrain['time'] = le3.fit_transform(xtrain['time'])
xtest['time'] = le3.transform(xtest['time'])

In [ ]:
xtest.head()

total_bill   tip  smoker  day  time  size
162       16.21  2.00       0  Sun     0     3
60        20.29  3.21       1  Sat     0     2
61        13.81  2.00       1  Sat     0     2
63        18.29  3.76       1  Sat     0     4
69        15.01  2.09       1  Sat     0     2

In [ ]:
## One Hot Encoding
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ct = make_column_transformer((OneHotEncoder(),['day']), remainder = 'passthrough')

In [ ]:
import sys
import numpy as np
np.set_printoptions(threshold = sys.maxsize)
xtrain = ct.fit_transform(xtrain)
xtest = ct.transform(xtest)

In [ ]:
xtest[:7]

array([[ 0.  ,  0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  , 19.49,  3.51,  0.  ,  0.  ,  2.  ]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(xtrain, ytrain)
y_pred = gnb.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(confusion_matrix(y_pred, ytest))
print(accuracy_score(y_pred, ytest))
print(classification_report(y_pred, ytest))

[[12  9]
 [12 41]]
0.7162162162162162
              precision    recall  f1-score   support

      Female       0.50      0.57      0.53        21
        Male       0.82      0.77      0.80        53

    accuracy                           0.72        74
   macro avg       0.66      0.67      0.66        74
weighted avg       0.73      0.72      0.72        74

